src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Enum\PaymentStatusEnum;
use App\Enum\TaxByCountryEnum;
use App\Repository\OperationRepository;
use Brick\Money\Money;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Webmozart\Assert\Assert;

#[ORM\Entity(repositoryClass: OperationRepository::class)]
class Operation
{
    #[ORM\Id]
    #[ORM\Column(type: Types::GUID, unique: true)]
    private UuidInterface|string $id;

    #[ORM\Column(length: 255, enumType: PaymentStatusEnum::class)]
    private PaymentStatusEnum $status;

    #[ORM\Column(type: Types::INTEGER)]
    private int $price;

    #[ORM\Column(length: 3)]
    private string $priceCurrency;

    #[ORM\Column(type: Types::INTEGER)]
    private int $tax;

    #[ORM\Column(length: 3)]
    private string $taxCurrency;

    #[ORM\Column(length: 255)]
    private string $taxNumber;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private \DateTimeInterface $createdAt;

    public function __construct(
        string $taxNumber,
        Money $price
    ) {
        $this->setTax($this->calculateTax($price, $taxNumber));
        $this->setPrice($price);
        $this->setTaxNumber($taxNumber);
        $this->id = Uuid::uuid4();
        $this->status = PaymentStatusEnum::NEW;
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getStatus(): PaymentStatusEnum
    {
        return $this->status;
    }

    public function checkout(): self
    {
        $this->status = PaymentStatusEnum::PAID;

        return $this;
    }

    public function getPrice(): Money
    {
        return Money::ofMinor($this->price, $this->priceCurrency);
    }

    private function setPrice(Money $price): self
    {
        $this->price = $price->getMinorAmount()->toInt();
        $this->priceCurrency = $price->getCurrency()->getCurrencyCode();

        return $this;
    }

    public function getTax(): Money
    {
        return Money::ofMinor($this->tax, $this->taxCurrency);
    }

    private function setTax(Money $tax): self
    {
        $this->tax = $tax->getMinorAmount()->toInt();
        $this->taxCurrency = $tax->getCurrency()->getCurrencyCode();

        return $this;
    }

    public function getTaxNumber(): string
    {
        return $this->taxNumber;
    }

    private function setTaxNumber(string $taxNumber): self
    {
        Assert::regex(
            $taxNumber,
            TaxByCountryEnum::getRegex(),
            'Invalid tax number'
        );
        $this->taxNumber = $taxNumber;

        return $this;
    }

    private function parseTaxNumber(string $taxNumber): string
    {
        return substr($taxNumber, 0, 2);
    }

    private function calculateTax(Money $price, string $taxNumber): Money
    {
        $countryCode = $this->parseTaxNumber($taxNumber);
        $tax = $price->getMinorAmount()->toInt() * TaxByCountryEnum::taxByCountry($countryCode);

        return Money::ofMinor($tax, $price->getCurrency()->getCurrencyCode());
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getTotal(): Money
    {
        return $this->getPrice()->plus($this->getTax());
    }
}

src/Controller/DefaultController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Operation;
use App\Form\CheckoutFormType;
use App\Form\OrderFormType;
use App\Repository\OperationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/', name: 'app_default_')]
class DefaultController extends AbstractController
{
    #[Route('/', name: 'orderform')]
    public function orderForm(
        Request $request,
        EntityManagerInterface $em
    ): Response {
        $form = $this->createForm(OrderFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            dump(__METHOD__);
            /** @var Operation $data */
            $data = $form->getData();
            $em->persist($data);
            $em->flush();

            return $this->redirectToRoute('app_default_confirm', ['uuid' => $data->getId()]);
        }

        return $this->render(
            'default/order_form.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    #[Route(
        '/confirm-payment/{uuid}',
        name: 'confirm',
        methods: ['GET', 'POST']
    )]
    public function confirmOrder(
        string $uuid,
        Request $request,
        OperationRepository $operationRepository,
    ): Response {
        $orderId = $request->get('uuid');
        $operation = $operationRepository->find($orderId);
        if (!$operation) {
            throw $this->createNotFoundException('Order not found');
        }
        $form = $this->createForm(CheckoutFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            return $this->redirectToRoute('app_default_congratulations');
        }

        return $this->render('default/checkout_form.html.twig', [
            'operation' => $operation,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/congratulations', name: 'congratulations')]
    public function congratulations(): Response
    {
        return $this->render('default/congratulations.html.twig');
    }
}

templates/default/checkout_form.html.twig
{% extends 'default/layout.html.twig' %}
{% block content %}
    <div class="row">
        <div class="col">
            <h4 class="mb-3">Order details</h4>
            <ul>
                <li>ID: {{ operation.id }}</li>
                <li>Date: {{ operation.createdAt|date('d/m/Y') }}</li>
                <li>Tax number: {{ operation.taxNumber }}</li>
                <li>Price: {{ operation.price }}</li>
                <li>Tax: {{ operation.tax }}</li>
                <li>Total price (tax included): <span class="text-decoration-underline">{{ operation.total }}</span></li>
            </ul>
        </div>
        <div class="col ">
            <h4 class="mb-3">Payment details</h4>
            {{ form_start(form) }}
            <div class="my-3">
                {{ form_widget(form.paymentMethod) }}
            </div>

            <div class="row gy-3">
                <div class="col">
                    {{ form_row(form.cardNumber) }}
                </div>
            </div>
            <div class="row gy-3">
                <div class="col">
                    {{ form_row(form.expiration) }}
                </div>

                <div class="col">
                    {{ form_row(form.cvv) }}
                </div>
            </div>
            <div class="row gy-3">
                <div class="col">
                    {{ form_row(form.ownerName) }}
                </div>
            </div>

            <hr class="my-4">

            {{ form_row(form.checkout) }}
            {{ form_end(form) }}
        </div>
    </div>


{% endblock %}

templates/default/congratulations.html.twig
{% extends 'default/layout.html.twig' %}
{% block body %}
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold">Congratulations, your order has been paid</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">
                Your order is already being prepared for shipment. A receipt of payment has been sent to your mail.
                There you can also find instructions to track the status of your order
            </p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="{{ path('app_default_orderform') }}" class="btn btn-primary btn-lg px-4 gap-3">Order more!</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/form.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <main>
            <div class="py-5 text-center">
                <h2>Checkout form</h2>
                <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
            </div>

            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Your cart</span>
                        <span class="badge bg-primary rounded-pill">3</span>
                    </h4>
                    <ul class="list-group mb-3">
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">Product name</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$12</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">Second product</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$8</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">Third item</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$5</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between bg-light">
                            <div class="text-success">
                                <h6 class="my-0">Promo code</h6>
                                <small>EXAMPLECODE</small>
                            </div>
                            <span class="text-success">−$5</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>$20</strong>
                        </li>
                    </ul>

                    <form class="card p-2">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Promo code">
                            <button type="submit" class="btn btn-secondary">Redeem</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Billing address</h4>
                    <form class="needs-validation" novalidate="">
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="firstName" class="form-label">First name</label>
                                <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <label for="lastName" class="form-label">Last name</label>
                                <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="username" class="form-label">Username</label>
                                <div class="input-group has-validation">
                                    <span class="input-group-text">@</span>
                                    <input type="text" class="form-control" id="username" placeholder="Username" required="">
                                    <div class="invalid-feedback">
                                        Your username is required.
                                    </div>
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                                <input type="email" class="form-control" id="email" placeholder="you@example.com">
                                <div class="invalid-feedback">
                                    Please enter a valid email address for shipping updates.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="address" class="form-label">Address</label>
                                <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
                                <div class="invalid-feedback">
                                    Please enter your shipping address.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
                                <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                            </div>

                            <div class="col-md-5">
                                <label for="country" class="form-label">Country</label>
                                <select class="form-select" id="country" required="">
                                    <option value="">Choose...</option>
                                    <option>United States</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please select a valid country.
                                </div>
                            </div>

                            <div class="col-md-4">
                                <label for="state" class="form-label">State</label>
                                <select class="form-select" id="state" required="">
                                    <option value="">Choose...</option>
                                    <option>California</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please provide a valid state.
                                </div>
                            </div>

                            <div class="col-md-3">
                                <label for="zip" class="form-label">Zip</label>
                                <input type="text" class="form-control" id="zip" placeholder="" required="">
                                <div class="invalid-feedback">
                                    Zip code required.
                                </div>
                            </div>
                        </div>

                        <hr class="my-4">

                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="same-address">
                            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
                        </div>

                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="save-info">
                            <label class="form-check-label" for="save-info">Save this information for next time</label>
                        </div>

                        <hr class="my-4">

                        <h4 class="mb-3">Payment</h4>

                        <div class="my-3">
                            <div class="form-check">
                                <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked="" required="">
                                <label class="form-check-label" for="credit">Credit card</label>
                            </div>
                            <div class="form-check">
                                <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
                                <label class="form-check-label" for="debit">Debit card</label>
                            </div>
                            <div class="form-check">
                                <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                                <label class="form-check-label" for="paypal">PayPal</label>
                            </div>
                        </div>

                        <div class="row gy-3">
                            <div class="col-md-6">
                                <label for="cc-name" class="form-label">Name on card</label>
                                <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                                <small class="text-muted">Full name as displayed on card</small>
                                <div class="invalid-feedback">
                                    Name on card is required
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label for="cc-number" class="form-label">Credit card number</label>
                                <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                                <div class="invalid-feedback">
                                    Credit card number is required
                                </div>
                            </div>

                            <div class="col-md-3">
                                <label for="cc-expiration" class="form-label">Expiration</label>
                                <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                                <div class="invalid-feedback">
                                    Expiration date required
                                </div>
                            </div>

                            <div class="col-md-3">
                                <label for="cc-cvv" class="form-label">CVV</label>
                                <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                                <div class="invalid-feedback">
                                    Security code required
                                </div>
                            </div>
                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                    </form>
                </div>
            </div>
        </main>

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">© 2017–2021 Company Name</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>
{% endblock %}

templates/default/layout.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <main>
            <div class="py-5 text-center">
                <h2>Order form</h2>
            </div>
            {% block content %}
                [Empty content]
            {% endblock %}
        </main>
        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">© 2013 &mdash; {{ 'now'|date('Y') }} Nikolay Deriglazov (@tprogger, @nkl90)</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>
{% endblock %}

templates/default/order_form.html.twig
{% extends 'default/layout.html.twig' %}
{% block content %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}